print("Budget Planner!")
income = (input("Please enter your net monthly income: $"))
housing = (input("Enter your monthly housing expense (rent or mortgage): $"))
utilities = (input("Enter your monthly utilities expense: $"))
groceries = (input("Enter your monthly groceries expense: $"))
transportation = (input("Enter your monthly transportation expense: $"))
health_care = (input("Enter your monthly health care expense: $"))
personal_care = (input("Enter your monthly personal care expense: $"))
clothing = (input("Enter your monthly clothing expense: $"))
debt = (input("Enter your monthly debt payments: $"))

print(f"Net Monthly Income: $2500")
print(f"Total Expenses: $2000 ")
print(f"Remaining Balance: $500\n")